language: node_js

node_js:
  - '10.15.0'

install:
  - npm install -g firebase-tools
  - yarn install

script:
  - echo "========== Build Start =========="
  - yarn run build

branches:
  only:
    - master

cache: yarn

after_success:
  - firebase deploy --token $FIREBASE_TOKEN